spring.application.name=WorldWatch
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/worldwatch_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash-lite

exchangerate.api.key=${EXCHANGE_RATE_API_KEY}
news.api.key=${NEWS_API_KEY}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000